###Get for as is data
GET http://localhost:7016/api/{{sample}}

###Get for data transformed to Modal data
GET http://localhost:7016/api/{{sample}}/FromModal

###Get for data transformed to Modal data and Uuid also
GET http://localhost:7016/api/{{sample}}/FromModalUuid

###Get for data transformed to Modal data , Uuid and timeStamp also
GET http://localhost:7016/api/{{sample}}/FromModalUuidAndTS

###

POST http://localhost:7016/api/{{sample}}/BodyCheck
content-type: application/json

###

POST http://localhost:7016/api/{{sample}}
content-type: application/json

{

}

###

POST http://localhost:7016/api/{{sample}}/FromModal
content-type: application/json

{

}